version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    bash -c "mvn -DskipTests -f shared-dependencies/pom.xml deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests -f spring-boot/pom.xml deploy --settings .travis-settings.xml";
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    bash -c "mvn -DskipTests -f shared-dependencies/pom.xml deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests clean install"
    bash -c "mvn -DskipTests -f spring-boot/pom.xml clean install";
    fi
env:
  global:
    - secure: "8JNqdFdCqhKA8XuTf7OctTIxM9XS8W1sE8fCI7ALBjXiVfSEw0Qnv5DTdtwL6HnzYV3Xn3zw62jgGQ/TnjAyZ1mCOm2j1cJciS+DXL2GE2phS9+PRbeRoIibzlRB08SHKDxK5st6NkszK06qFePEJTyVNgxQxOyPqVIB2MAhganEahzBn7HfDDwiPRzUZsaJZagdTtS1xlgD239JscsCrLXpviHUfPS7SyHkB2HMrsux7LIpKmINfeFbnKiNOvM+hbRD08rv7mCEQY8Chin0xFnBZBBKcby/vrV+bs6t3Y6CCiRz7t6rufTeLBWpVUJUOixzNWZzLxThPa7Rj1qpIvLk2a0g2jjY5hEQ+c5ugtuUjN3eK309XW0DmX9VqRhMAGbaTy1djy36MtDE1l8iqKpATKo0kwXjEmVv3qj5QgfVWj+1f3zzXtJH3r3H/TEq5zj3Ee9JaFQkGX/1N6bRDyIHaS+sVj1ljCgQCasDrFRH7YR7CWg6flMtwsGEf3Eu0AiemBNLuI+fp2xeAzdarmjW/v3cL9+wbIQhSo28nN0WGHu0I6PIp6153QQMrALi1XYMu/neG0F732SelRsPGMwxH1HhSsJYp6AjfKSnJmMBNbumrmTQQW4xpYzfCswteTLabu6Rca2inKHXPokwlenrH3Z6qTr3DwEWd1ss8iY="
    - secure: "A+Fd6bmL5QjEL9bsnk6FcsZn+Q/1VEdKSrVtmSJUuZnr11z6p3194DByRKHFLI0+hEBv9/shZh1ZhOYHiHxTrzrvBqVjSYJ+1dk/R1d77OBwtrUCNWtpl7+iW0hEMw3ymmQEyKRwgF3/AgNQ3Tlj66Gdk2OyjM0WfAaNUnN5o1IDUAzP5xeZaF6q2F/lK2Xk7Tpgot7YEwsWhpQyyap0gOa2VtEUpTKk3mPHJ1hud5wCoC0Ewu7K4V/16nQ29WzUuSsgdQBHfbpIRcTgrRx0UYl/mkJriRAVLH1xmxW9EoflNnAmEI7MXMJtZsdfNFBjETv4Hs8xguC7XaTvtoRAvR2/c6XMJJhcXetYqmGAxB/BpEJEhVd7jpIOTc3Q81uaAhbv+1G7IHUwDZphj/sdqyCFeytriJJpmEuME3WFk5SuuYiCxAcXhpuCTRUilltFAGHB2AAWNgA7Rgzg3pisj7XvUPksmsFuRvi5RqgDluNuX2YHMjXaS/wRcBxGBacZV1vVxrVaLvZ5wfDGgvlqHnsoGyRRdGCIIIYDC7Gcn+vaJstXMwsvrr/fOvwmYpWlQOSSNsRd271rXi+QZuBSHA5LgTdSNMuFGuzSD5F4PxZwk3XBsnJEyZ8P+zcW1PJKtB7R3UesbCYAkxJenfE73/9+/b7RtyFcMVPRFbYYgfY="
