version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    bash -c "mvn -DskipTests -f shared-dependencies/pom.xml deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests -f pom-spring-boot.xml deploy --settings .travis-settings.xml";
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    bash -c "mvn -DskipTests -f shared-dependencies/pom.xml deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests clean install"
    bash -c "mvn -DskipTests -f pom-spring-boot.xml clean install";
    fi
env:
  global:
    - secure: "okW9l3kVOeCnFHbJmlok81E0wws5k1Qq/NYz8ZhoG6fD0zE86zExouFTasNlAnxr2wEI6LwKecl8cB90DFIGgytdxrgCF3PO5GBrxa8HPMciDFet6U704FyBBNd/B2+5oEStKUNqyvn7YduQyL3JcR9qmwE9tG3KIdjbdcf/dNeYfv4Sb5vdLY3diuwNDukZN3Nf2n2jhZO3OQZ4SS5AZsSAwD1oOZwr/SZczZQMpIA9KKHKRR4SJ9107TeaFJ7bmRMITC6fJYxDrAh2261hU83wwYPscbzpQ5QzD47e2dZkFj6j9L2Lo6Jsco5noUnyhUEOX9OWZEhQkENEQhcQDhRtbd6qkyWeTKxhDLRj5BSy0+sVT1/Wp0VqnIAR3iUo5Q3tZErnZv3AHI1N/ppJSSOXBDUpg3pKiOmqbduaUlpYEcy0/A3L0NjlfLCUyUFM2EgsCc2+gKMGbnAmi/KZ0SUwyR3xiFohfslUbAfGc8cAYYOEMn1g90WXLvrJfkYUwLKWBVVptMeaP10T8giY6+cnOUupNW+W77bak0jPuJNJJilWLEse/Sr8B7LyZrSV5OEtr12G3oQxG04631cliedAaTCg9fT0iS6R0X9+eiqDYWLOlDIyseKvlPwN0uWsDQQJXBryUinzMR08fmxRncl7WslvK/9n6mjWMz92flM="
    - secure: "4j1dIzE7O2o33zZnHHiZWGgCpsP/0YNX3ocWiif4vWk92dT3J/XbBQIyI1Bcwc8Z4yuhPZs+/a7cXoxqh7v7mMYdkK0uNmq7Xroy28hoXldWTUBGXe8nkLqYdZqJC483tpk8AfgH6SGa1yDOqDaslW4FO8LuxSRhqF05mMm9Y9jx5HM04gsKVFW7sahatGcok8YhERdXMtdkvfDAFgYGCh9Rv+WX4AyOf14cSF4K02a9pC2DAsmA9o/Q/LVOKzC90qKOn21RSBZK7yz+GGhAw6XP6GmRXaU6bjJ7sKvoBf2u8sVc20CwSB8sSA3lDqOy+/xYzekYxqf8+ZsApLZ4rIvlLl23lOChrBdXe8tQmUfx3vUwo53GxEznUEdF0cBXI0aqR+/W3JAUIJnWez3dIrXdOTPRAXyECXpSu+ZMOG0nIy6M4B2WYg5yMbIBbE08lArW/03oWzvlifNK+yrQLuw1WNpktuPcGf7UbBBPVj0eXDW+pAiy3j6OToeOixqKndbWYKeaGeCQIETzO9mrlI/X/hYW7+3O1dMJowR6scq2ekq8xGyIZeCt9IUWyKQ9Usjt5eHgKsrfDvl1aYPV1MkL0xPHcekhekR2Ag6TNvWOOB+SuMKCtZMT00goBt8B1s8gzMVSmz4qVkOghIIZ4+LEyMCSNzjaBwqu/5YI9lc="
