/*
 * Copyright (C) 2007-2026 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Shared configuration for CrafterCMS Java library modules.
 */

plugins.withType(JavaPlugin).configureEach {
	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(javaVersion.toInteger())
		}
		withSourcesJar()
		withJavadocJar()
	}

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
		options.compilerArgs += ['-parameters']
	}

	tasks.withType(Javadoc).configureEach {
		options.addStringOption('Xdoclint:syntax', '-quiet')
	}

	tasks.withType(Test).configureEach {
		useJUnit()
	}

	group = 'org.craftercms'
	version = craftercmsVersion
}

apply from: "${rootDir}/gradle/test-classpath.gradle"
apply from: "${rootDir}/gradle/maven-publish.gradle"
apply from: "${rootDir}/gradle/bom.gradle"
