/*
 * Copyright (C) 2007-2026 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
	id 'java-library'
}

apply from: "${rootDir}/gradle/java-library.gradle"

base {
	archivesName = 'crafter-commons-git'
}

dependencies {
	compileOnly libs.jgit
	compileOnly libs.jgit.archive
	implementation libs.jgit.ssh.apache
	implementation libs.bcpg.jdk18on
	implementation libs.bcpkix.jdk18on
	implementation libs.bcprov.jdk18on
	implementation libs.eddsa
	compileOnly libs.commons.lang3
	implementation libs.commons.io
	compileOnly libs.slf4j.api
	compileOnly libs.jcl.over.slf4j

	testImplementation libs.jgit
	testImplementation libs.jgit.archive
	testImplementation libs.commons.lang3
	testImplementation libs.slf4j.api
	testImplementation libs.jcl.over.slf4j

	testImplementation libs.junit
	testImplementation libs.spring.webmvc
	testImplementation libs.spring.test
	testImplementation libs.mockito.core
	testImplementation libs.commons.collections4
	testImplementation libs.slf4j.simple
}
