/*
 * Copyright (C) 2007-2026 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
	id 'java-library'
}

apply from: "${rootDir}/gradle/java-library.gradle"

base {
	archivesName = 'crafter-profile-api'
}

dependencies {
	implementation project(':commons:security')
	implementation project(':commons:utilities')

	implementation libs.commons.lang3
	implementation libs.mongo.bson
	implementation libs.spring.core
	implementation libs.jackson.databind
}
